version: '2'
services:
  # mysql
  mysql:
    image: mysql:5.7
    volumes:
       - /var/volumes/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
